service: country-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["CountriesTable", "Arn"] }

functions:
  createProduct:
    handler: src/handlers.createCountry
    events:
      - httpApi:
          path: /country
          method: post
  getProduct:
    handler: src/handlers.getCountry
    events:
      - httpApi:
          path: /country/{id}
          method: get
  updateProduct:
    handler: src/handlers.updateCountry
    events:
      - httpApi:
          path: /country/{id}
          method: put
  deleteProduct:
    handler: src/handlers.deleteCountry
    events:
      - httpApi:
          path: /country/{id}
          method: delete
  listProduct:
    handler: src/handlers.listCountry
    events:
      - httpApi:
          path: /country
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    CountriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CountriesTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: countryID
            AttributeType: S
        KeySchema:
          - AttributeName: countryID
            KeyType: HASH
